insert into LOCATION (price, currency, name, address, city, state, zip, country) values (25.00, 'GBP', 'Heathrow Airport', 'Terminal 4', 'Hillingdon', 'Greater London', 'TW6 3', 'UK');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (15.00, 'GBP', 'Gatwick Airport', 'South Terminal', 'Gatwick', 'West Sussex', 'RH6 0RN', 'UK');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (20.00, 'USD', 'John F. Kennedy Airport', 'Van Wyck Expy and JFK Expy', 'Queens', 'NY', '11422', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (20.00, 'USD', 'Washington Dulles International Airport', 'None', 'Washington', 'DC', '20041', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (20.00, 'USD', 'W Hotel', 'Union Square, Manhattan', 'NY', 'NY', '10011', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (15.00, 'USD', 'Hotel Rouge', '1315 16th Street NW', 'Washington', 'DC', '20036', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (10.00, 'USD', 'Conrad Miami', '1395 Brickell Ave', 'Miami', 'FL', '33131', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (8.00,  'USD', 'Super 8 Eau Claire Campus Area', '1151 W Macarthur Ave', 'Eau Claire', 'WI', '54701', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (12.00, 'USD', 'Marriot Downtown', '55 Fourth Street', 'San Francisco', 'CA', '94103', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (15.00, 'EUR', 'Hilton Diagonal Mar', 'Passeig del Taulat 262-264', 'Barcelona', 'Catalunya', '08019', 'Spain');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (10.00, 'ILS', 'Hilton Tel Aviv', 'Independence Park', 'Tel Aviv', 'None', '63405', 'Israel');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (20.00, 'JPY', 'InterContinental Tokyo Bay', 'Takeshiba Pier', 'Tokyo', 'None', '105', 'Japan');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (15.00, 'CHF', 'Hotel Beaulac', ' Esplanade Leopold-Robert 2', 'Neuchatel', 'None', '2000', 'Switzerland');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (10.00, 'USD', 'Conrad Treasury Place', 'William and George Streets', 'Brisbane', 'QLD', '4001', 'Australia');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (12.00, 'CAD', 'Ritz Carlton', '1228 Sherbrooke St', 'West Montreal', 'Quebec', 'H3G1H6', 'Canada');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (8.00,  'USD', 'Ritz Carlton', 'Peachtree Rd, Buckhead', 'Atlanta', 'GA', '30326', 'USA');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (10.00, 'AUD', 'Swissotel', '68 Market Street', 'Sydney', 'NSW', '2000', 'Australia');
insert into LOCATION (price, currency, name, address, city, state, zip, country) values (12.00, 'USD', 'Hotel Allegro', '171 West Randolph Street', 'Chicago', 'IL', '60601', 'USA');